name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker://xucheng/texlive-full
      with:
        entrypoint: latexmk
        args: -pdf dialogue
    - uses: actions/upload-artifact@v2
      with:
        name: dialogue
        path: dialogue.pdf
  pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker://pandoc/latex
      with:
        args: -s -f latex -t icml -o dialogue.icml --bibliography=dialogue.bib -C --csl=splncs.csl dialogue.tex
    - uses: actions/upload-artifact@v2
      with:
        name: dialogue
        path: dialogue.icml
